project:
  type: website

website:
  title: "Goat"
  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Miembros
      - href: tesoreria.qmd
        text: Aportes
      - href: reglas.qmd
        text: Reglas

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



